# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 25d04126dc7c0bc8e08d2ec96685ead5bdbea91c30e23c3c58c914532de85062a947cde0d31046968d2402c5618f4d88a223fe5b3a53eca6c381f4313f1c2977

test:
  secret_key_base: 53c44d8879fffdd60cc9cb5b06409ce9cd0465222a7d694d36da58cbddf8f7280cd2a19db174d8162bfc2dcbc172e08ee33ebb84b1c74430a76e8bb4ba56f36a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
